// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8btbnDnPpGgDMwAoJnQdOsftEejMvUE',
    appId: '1:687601632005:android:d11b5ac6ff234039eead6c',
    messagingSenderId: '687601632005',
    projectId: 'axperthybrid',
    storageBucket: 'axperthybrid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6TxtF1ADjdt-qEpwtCxw3OfwVVy-Csw',
    appId: '1:687601632005:ios:338dafab5d240b04eead6c',
    messagingSenderId: '687601632005',
    projectId: 'axperthybrid',
    storageBucket: 'axperthybrid.appspot.com',
    androidClientId: '687601632005-6q8ikv3vtt7oclch2mt7fsdfev3a96ar.apps.googleusercontent.com',
    iosClientId: '687601632005-bfc005cvu87naen834r3p2bb73v8jhgv.apps.googleusercontent.com',
    iosBundleId: 'com.agile.axpertios',
  );
}
